# Generated by Django 4.2 on 2023-04-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lti1p3_tool_config', '0002_alter_ltitool_id_alter_ltitoolkey_id'),
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name', max_length=120)),
                ('register_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the course first appeared in our system')),
                ('attempts', models.PositiveSmallIntegerField(default=3, help_text='Number of attempts a student has for the assignment')),
                ('course', models.ForeignKey(help_text='Relation to corresponding course on an LTI Platform', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='canvas.course')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, help_text='Internal deployment ID', primary_key=True, serialize=False)),
                ('lti_deployment_id', models.CharField(help_text='LTI Deployment ID', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('svg_route', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='User email', max_length=254, unique=True)),
                ('ltiConfig', models.ForeignKey(help_text='Relation to corresponding tool deployment on an LTI Platform', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ltiConfig', to='lti1p3_tool_config.ltitool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user_input', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField()),
                ('state', models.PositiveSmallIntegerField()),
                ('assignment', models.ForeignKey(help_text='Relation to corresponding assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.assignment')),
                ('user', models.ForeignKey(help_text='Relation to corresponding user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='canvas.ltiuser')),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField()),
                ('assignment', models.ForeignKey(help_text='Relation to corresponding assignment', on_delete=django.db.models.deletion.CASCADE, related_name='related_assignment', to='api.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.game'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='required_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needed_assignment', to='api.assignment'),
        ),
    ]
