# Generated by Django 4.2a1 on 2023-03-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_alter_course_register_date'),
        ('api', '0002_toolcourse_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_created=True, help_text='Timestamp when the course first appeared in our system')),
                ('name', models.CharField(help_text='Course name', max_length=120)),
                ('rounds', models.SmallIntegerField()),
                ('course', models.ForeignKey(help_text='Relation to corresponding course on an LTI Platform', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='canvas.course')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ToolCourse',
        ),
        migrations.AddField(
            model_name='assignment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.game'),
        ),
    ]
