# Generated by Django 4.2 on 2023-05-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questionbank_assignment_question_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField()),
                ('question_bank', models.ForeignKey(help_text='Relation to corresponding bank', on_delete=django.db.models.deletion.CASCADE, to='api.questionbank')),
            ],
        ),
    ]
