# Generated by Django 4.1.7 on 2023-04-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
        ('api', '0002_alter_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name', max_length=120)),
                ('register_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the course first appeared in our system')),
                ('attempts', models.PositiveSmallIntegerField(default=3, help_text='Number of attempts a student has for the assignment')),
                ('course', models.ForeignKey(help_text='Relation to corresponding course on an LTI Platform', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='canvas.course')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField()),
                ('assignment', models.ForeignKey(help_text='Relation to corresponding assignment', on_delete=django.db.models.deletion.CASCADE, related_name='related_assignment', to='api.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user_input', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField()),
                ('state', models.PositiveSmallIntegerField()),
                ('assignment', models.ForeignKey(help_text='Relation to corresponding assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.assignment')),
                ('user', models.ForeignKey(help_text='Relation to corresponding user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='canvas.ltiuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='deployment',
        ),
        migrations.DeleteModel(
            name='LTIUser',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='assignment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.game'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='required_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needed_assignment', to='api.assignment'),
        ),
    ]
