# Generated by Django 4.2a1 on 2023-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
