# Generated by Django 4.2 on 2023-07-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questionbank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='question_bank',
            field=models.ForeignKey(blank=True, help_text='Relation to corresponding bank', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questionbank'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='Relation to corresponding assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_assignment', to='api.assignment'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
