# Generated by Django 4.2a1 on 2023-03-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
