# Generated by Django 4.2a1 on 2023-03-22 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_game_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_path',
        ),
    ]
