# Generated by Django 4.2 on 2023-07-23 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_gamedata_question_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 23, 16, 48, 10, 687380, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
