# Generated by Django 4.1.7 on 2023-08-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment_lineitem_url_assignment_resource_id'),
        ('api', '0007_questionbank_created_at_questionbank_updated_at'),
    ]

    operations = [
    ]
