# Generated by Django 4.2a1 on 2023-03-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_game_game_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='assignment',
            field=models.ForeignKey(default=1, help_text='Relation to corresponding assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.assignment'),
            preserve_default=False,
        ),
    ]
