# Generated by Django 4.2a1 on 2023-03-23 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_alter_course_register_date'),
        ('api', '0008_run_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(default=1, help_text='Relation to corresponding user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='canvas.ltiuser'),
            preserve_default=False,
        ),
    ]
