# Generated by Django 4.1.7 on 2023-09-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0002_alter_ltitool_id_alter_ltitoolkey_id'),
        ('api', '0008_merge_20230806_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ltiConfig',
        ),
        migrations.AddField(
            model_name='user',
            name='ltiConfigKey',
            field=models.ForeignKey(help_text='Relation to corresponding tool deployment on an LTI Platform', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ltiConfigKey', to='lti1p3_tool_config.ltitoolkey'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attempts',
            field=models.SmallIntegerField(help_text='Number of attempts a student has for the assignment'),
        ),
    ]
