# Generated by Django 4.2a1 on 2023-03-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_run_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.JSONField()),
                ('order', models.PositiveIntegerField()),
                ('right_answer', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(help_text='Relation to corresponding assignment', on_delete=django.db.models.deletion.CASCADE, related_name='related_assignment', to='api.assignment')),
            ],
        ),
    ]
