# Generated by Django 4.2a1 on 2023-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gamedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='state',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='register_date',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the course first appeared in our system'),
        ),
    ]
