# Generated by Django 4.2a1 on 2023-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_assignment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='user_input',
            field=models.JSONField(default={}),
        ),
    ]
