# Generated by Django 4.2a1 on 2023-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_gamedata_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='user_input',
            field=models.JSONField(default=dict),
        ),
    ]
