# Generated by Django 4.2a1 on 2023-03-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_gamedata_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of attempts a student has for the assignment'),
        ),
    ]
