# Generated by Django 4.2a1 on 2023-04-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_assignment_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='order',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='question',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='right_answer',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
