# Generated by Django 4.2 on 2023-04-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_gamedata_answers_remove_gamedata_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_required',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_needed', to='api.assignment'),
        ),
    ]
