# Generated by Django 4.2 on 2023-04-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_assignment_assignment_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_required',
        ),
        migrations.AddField(
            model_name='assignment',
            name='required_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needed_assignment', to='api.assignment'),
        ),
    ]
