# Generated by Django 4.2 on 2023-04-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_assignment_assignment_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='svg_route',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
