# Generated by Django 4.2 on 2023-04-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_game_svg_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
    ]
