# Generated by Django 4.2a1 on 2023-03-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, help_text='LTI User ID', primary_key=True, serialize=False)),
                ('lti_user_id', models.UUIDField(help_text='User sub as refered by the LTI platform')),
                ('name', models.CharField(blank=True, help_text='User name in LTI platform', max_length=50)),
                ('email', models.EmailField(help_text='User email in the LTI platform', max_length=254, unique=True)),
            ],
        ),
    ]
