# Generated by Django 4.1.7 on 2023-04-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuser',
            name='email',
            field=models.EmailField(help_text='User email in the LTI platform', max_length=254, null=True),
        ),
    ]
