# Generated by Django 4.2a1 on 2023-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_alter_ltiuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('register_date', models.DateTimeField(auto_created=True, help_text='Timestamp when the course first appeared in our system')),
                ('id', models.CharField(auto_created=True, help_text='LTI Course ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='LTI Course name', max_length=120)),
                ('deployment_id', models.BigIntegerField(help_text='Relation to corresponding deployment on an LTI Platform')),
            ],
        ),
    ]
