# Generated by Django 4.2a1 on 2023-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deployment_id',
            field=models.CharField(help_text='Relation to corresponding deployment on an LTI Platform'),
        ),
    ]
