# Generated by Django 4.2a1 on 2023-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_alter_course_deployment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='register_date',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the course first appeared in our system'),
        ),
    ]
