# Generated by Django 4.2a1 on 2023-03-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_alter_course_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='ltiuser',
            name='lti_user_id',
            field=models.UUIDField(help_text='User sub as refered by the LTI platform', primary_key=True, serialize=False),
        ),
    ]
