# Generated by Django 4.2a1 on 2023-03-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0006_remove_ltiuser_id_alter_ltiuser_lti_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuser',
            name='lti_user_id',
            field=models.UUIDField(help_text='User sub as referred by the LTI platform', primary_key=True, serialize=False),
        ),
    ]
