# Generated by Django 4.2 on 2023-04-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0007_alter_ltiuser_lti_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deployment_id',
            field=models.CharField(help_text='Relation to corresponding deployment on an LTI Platform', max_length=512),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(auto_created=True, help_text='LTI Course ID', max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ltiuser',
            name='email',
            field=models.EmailField(help_text='User email in the LTI platform', max_length=254, null=True),
        ),
    ]
