from .assignments import AssignmentsView
from .assignment_stats import AssignmentStatsView
from .games import GamesView
from .login import LoginView
from .register import RegisterView
from .questions import QuestionsView
from .question_bank import QuestionBankView
from .run import RunView
from .score import ScoreView
from .test import TestView
from .user_config import UserConfigView
